version: '3.8'

services:
  users-gorm-db:
    image: postgres
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: ${dbName}
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPassword}